project_id = "nswgubxabcjyfsgbiicz"

[functions]
  [functions.ai-search]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.order-reminders]
    verify_jwt = false
  [functions.payout-method-save]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.project-action]
    verify_jwt = false
  [functions.river-chat]
    verify_jwt = false
  [functions.send-marketplace-email]
    verify_jwt = false

  [functions.workflow-engine]
    verify_jwt = false
